spring:
  application:

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa1

  h2:
    console:
      enabled: true
      path: /h2-console/


  mail:
    host: smtp.gmail.com
    port: 587
    username: oskarjavatestingsender123321@gmail.com
    password: nwld htel ohhv fgkf
    properties.mail.smtp:
      auth: true
      starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: false
server:
  port: 8090
scheduled:
  cron-expression: "1 * * * * *"